FROM node:16.14.2
RUN npm i -g npm@latest

WORKDIR /usr/src/app

RUN npm i -g @nestjs/cli typescript ts-node
COPY package*.json ./

RUN npm install

COPY . .

COPY ./wait-for-it.sh /opt/wait-for-it.sh
COPY ./startup.dev.sh /opt/startup.dev.sh

CMD ["/bin/bash", "/opt/startup.dev.sh"]